import Head from "next/head";
import GetData from "../components/GetData";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const lat = 35.9621;
  const lon = -84.2916;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GetData lat={lat} lon={lon} />
      </main>
      <footer className={styles.footer}>
        <h4 className="title">
          <Link href="/page2">
            <a>Go to page2</a>
          </Link>
        </h4>
      </footer>
    </div>
  );
}
