import { useState } from "react";
import Head from "next/head";
import { fetchDaymet } from "../functions/fetchDaymet";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const lat1 = 35.9621;
  const lon1 = -84.2916;
  const [enteredLat, setEnteredLat] = useState("");
  const [enteredLon, setEnteredLon] = useState("");
  const [daymetData, setDaymetData] = useState(null);

  const text =
    daymetData === null ? "Loading..." : daymetData.data["tmax (deg c)"][0];

  function sendRequest(event) {
    event.preventDefault();
    fetchDaymet({ lat: enteredLat, lon: enteredLon, setDaymetData });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <GetData lat={enteredLat} lon={enteredLon} /> */}
        <form onSubmit={sendRequest} className={styles.form}>
          <label htmlFor="lat">Latitude</label>
          <input
            id="lat"
            type="text"
            required
            value={enteredLat}
            onChange={(event) => setEnteredLat(event.target.value)}
          />
          <label htmlFor="lon">Longitude</label>
          <input
            id="lon"
            type="lon"
            required
            value={enteredLon}
            onChange={(event) => setEnteredLon(event.target.value)}
          />
          <button type="submit">Get Temperature</button>
        </form>

        <>
          <h3>The tmax is:</h3>
          <h3>{text}</h3>
        </>
      </main>
      <footer className={styles.footer}>
        <h4 className="title">
          <Link href="/page2">
            <a>Go to page2</a>
          </Link>
        </h4>
      </footer>
    </div>
  );
}
