import { useState } from "react";
import Head from "next/head";
import { fetchDaymet } from "../functions/fetchDaymet";
import styles from "../styles/Home.module.css";
import Link from "next/link";
//import Map from "../components/Map";
import dynamic from "next/dynamic";

const Map = dynamic(() => import("../components/Map"), {
  ssr: false,
});

export default function Home() {
  const lat1 = 35.9621;
  const lon1 = -84.2916;
  const [enteredLat, setEnteredLat] = useState("");
  const [enteredLon, setEnteredLon] = useState("");
  const [daymetData, setDaymetData] = useState(null);

  const text =
    daymetData === null ? "Loading..." : daymetData.data["tmax (deg c)"][0];

  function sendRequest(event) {
    event.preventDefault();
    fetchDaymet({ lat: enteredLat, lon: enteredLon, setDaymetData });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""
        />
        <script
          src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
          crossorigin=""
        ></script>
      </Head>

      <main className={styles.main}>
        {/* <GetData lat={enteredLat} lon={enteredLon} /> */}
        <form onSubmit={sendRequest} className={styles.form}>
          <div>
            <div>
              <label htmlFor="lat">Latitude</label>
              <input
                id="lat"
                type="text"
                required
                value={enteredLat}
                onChange={(event) => setEnteredLat(event.target.value)}
              />

              <div>
                <label htmlFor="lon">Longitude</label>
                <input
                  id="lon"
                  type="lon"
                  required
                  value={enteredLon}
                  onChange={(event) => setEnteredLon(event.target.value)}
                />
              </div>
              <button type="submit">Get Temperature</button>
            </div>
            <div id="map">
              <Map />
            </div>
          </div>
        </form>

        <>
          <h3>The tmax is:</h3>
          <h3>{text}</h3>
        </>
      </main>
      <footer className={styles.footer}>
        <h4 className="title">
          <Link href="/page2">
            <a>Go to page2</a>
          </Link>
        </h4>
      </footer>
    </div>
  );
}
